### ISSUE TITLE
Can't override JLToastViewValue.

### ISSUE THREAD

**Issue by ppinel** [devxoul/JLToast#16]
Hi,

I tried to override the value of the struct JLToastViewValue but I failed.
Can you modify the code to allow people to override the value in the struct pls?

Thanks

**Comment by devxoul** [comment]
I just add some code to support for setting default values. You can now set default values, e.g.

```swift
JLToastView.setDefaultValue(20, forAttributeName: JLToastViewFontSizeAttributeName, userInterfaceIdiom: .Phone)
```

For more info, see #17

Thanks.

**Comment by ppinel** [comment]
@devxoul Thank you!
