### ISSUE TITLE
File *.h is missing when installing the JLToast via CoccoaPods.

### ISSUE THREAD

**Issue by ppinel** [devxoul/JLToast#18]
Hi,

It appear that in the pod config file you specify only the ``*.swift`` file to be installed.
https://github.com/devxoul/JLToast/blob/master/JLToast.podspec#L11
So the ``JLToast.h`` is missing.

Can you fixed it pls?
``s.source_files = 'JLToast/*.swift'`` to ``s.source_files = 'JLToast/*.{swift,h}'``

Thanks!

**Comment by devxoul** [comment]
Thanks for your report! `JLToast.h` file must be included in `public_header_files`, too. For details, see #19.
