### ISSUE TITLE
Don't working at Alamofire

### ISSUE THREAD

**Issue by Realignist** [devxoul/JLToast#23]
I am using for JLToast with Alamofire in swift project. 
But it doesn't works in Alamofire Closure. It can catch on debugger, but not working.

Can I help for this issue?

```swift
Alamofire.request(.POST, "...", parameters: [...]).responseJSON { (req, res, data, err) in
    var json = JSON(data!)
    println(json)
    if (json["status"].stringValue == "error") {
        // Doesn't works!
        JLToast.makeText("...").show();
    } else {
         ...
    }
}
```

**Comment by devxoul** [comment]
I just tested with your code but it seemed to work. Could you please tell me your environment? (such as swift version, JLToast version)

**Comment by Realignist** [comment]
I just used on Xcode 6.2. JLToast's version was 1.1.1.
May I have to move swift to 1.2?

**Comment by devxoul** [comment]
Actually swift 1.2 is official now, can you try with swift 1.2?
