### ISSUE TITLE
Possible to use with iOS 7.0?

### ISSUE THREAD

**Issue by blakeperdue** [devxoul/JLToast#26]
With iOS 7.0 still at over 16% of the market, I have to support it unfortunately. Is there a quick way to get JLToast to support iOS 7?

**Comment by devxoul** [comment]
@blakeperdue, Of course you can.

Just download the source code, then import to your project. Dynamic framework via CocoaPods or Carthage will be rejected by Apple.

**Comment by blakeperdue** [comment]
Awesome, thanks for the tip!

**Comment by devxoul** [comment]
No problem :)
