### ISSUE TITLE
Toast Doesn't Appear Inside CollectionView didSelectItemAtIndexPath

### ISSUE THREAD

**Issue by mikewalkerjr** [devxoul/JLToast#27]
I have a UICollectionView where I let the user select up to 5 photos. After 5 are selected I'm trying to show a toast message informing the user only 5 photos can be selected. I am using JLToast throughout the code, however here it does not show. The UICollectionView is within a UIViewController. Here is the code I am using within didSelectItemAtIndexPath:

            println("show toast")
            JLToast.makeText(NSLocalizedString("select_up_to_five_photos", comment: "Select up to 5 photos")).show()            

The println gets printed correctly, but I don't see a toast.

**Comment by devxoul** [comment]
Your code doesn't seem to have any problem. Could you please let me know more context? I can't figure out the problem with your code.
Thanks!

**Comment by mikewalkerjr** [comment]
I actually was playing with the code some and it actually has to do with how the ViewController is presented. Originally I had used navigationController.presentViewController, and using that I was not able to see a Toast message. 

If I changed the code to use navigationController.pushViewController, then the toast works properly.

**Comment by devxoul** [comment]
You mean the toast message from modal view controller won't be shown?

**Comment by mikewalkerjr** [comment]
Yes that's correct

**Comment by devxoul** [comment]
Could you please test with this?

Replace the line 104 at `JLToast.swift`:

**Before**
```swift
UIApplication.sharedApplication().keyWindow?.subviews.first?.addSubview(self.view)
```

**After**
```swift
UIApplication.sharedApplication().windows.first?.addSubview(self.view)
```

If it works, I'll make a new release.

**Comment by mikewalkerjr** [comment]
Yes that fixed it.

**Comment by devxoul** [comment]
Great. Then I'll make a new release. Thanks!
