### ISSUE TITLE
Toast appears behind keyboard, not visible to user

### ISSUE THREAD

**Issue by ArtworkAD** [devxoul/JLToast#31]
If the software keyboard is visible toast message appear behind the keyboard not in front of it.

Use case: validation of text inside text field. You want the keyboard to be present however you also want to display a toast. BUT the toast should not block interaction with keyboard.

**Comment by devxoul** [comment]
Hi @ArtworkAD,

I've just made a new PR for this issue: https://github.com/devxoul/JLToast/pull/32
Could you please check this?

Thanks :smile:

**Comment by ArtworkAD** [comment]
@devxoul It works perfectly. However there is a little issue with with the opacity. I would like to reduce opacity to make the text more readable, but only when I show it over a keyboard. Is this possible? I would like to do e.g.

JLToast.makeText("FooBar", opacity: 0.95).show()

**Comment by devxoul** [comment]
@ArtworkAD,

You can access `JLToastView` from `JLToast` instance then set `alpha`.

```swift
let toast = JLToast.makeText("FooBar")
toast.view.alpha = 0.95
toast.show()
```

**Comment by ArtworkAD** [comment]
@devxoul thank you, please upload this update to cocoapods :dancer:

**Comment by devxoul** [comment]
@ArtworkAD 
Finished! https://cocoapods.org/pods/JLToast :smile:

**Comment by ArtworkAD** [comment]
The keyboard issue appears in iOS9 again. The toast is behind the keyboard.

**Comment by devxoul** [comment]
@ArtworkAD, I've made a new PR to fix this issue: #42

**Comment by ArtworkAD** [comment]
@devxoul :smile: just tested, it works. Please merge and update to cocoapods. Grazi :+1:

**Comment by devxoul** [comment]
@ArtworkAD, https://github.com/devxoul/JLToast/releases/tag/1.3.1
:smile:
