### ISSUE TITLE
Feature Request: Introduce color types

### ISSUE THREAD

**Issue by ArtworkAD** [devxoul/JLToast#34]
Would like to do:

    JLToast.makeText("FooBar", type: JLToastType.Green).show()

with types:

    JLToastType.Green
    JLToastType.Red
    JLToastType.Black (default)

or other example:

    JLToast.makeText("FooBar").show(JLToastType.Green)

or

    JLToast.makeText("FooBar").showSuccess()

Use-case: I want to make toasts more meaningful like "this is an error" or "entry created successfully". I know there is a way to customize the background but my suggestion would make it easier.

We should be able to customize those types.

**Comment by devxoul** [comment]
As we did in #31, you can set background color of `JLToastView`. For reusable purpose, you can make a wrapper class for it.

```
class MyToast {

    public class func showSuccess(text: String) {
        let toast = JLToast.makeText(text)
        toast.view.backgroundColor = UIColor.greenColor()
        toast.show()
    }

}
```

**Comment by ArtworkAD** [comment]
lel :smile: thank you
