### ISSUE TITLE
Custom background color issue

### ISSUE THREAD

**Issue by ArtworkAD** [devxoul/JLToast#35]
![foto 03 08 15 12 20 21](https://cloud.githubusercontent.com/assets/524580/9035681/6ef0b2a2-39da-11e5-83e6-807882e5ad0e.png)

when I present it like this:
```
class func showError(text: String) {
    let toast = JLToast.makeText(text)
    toast.view.backgroundColor = UIColor.redColor()
    toast.duration = JLToastDelay.LongDelay
    toast.show()
}
```

    MyToast.showError(err)

It seems like the black color is overlaying the red color.

**Comment by devxoul** [comment]
Oh, I'm sorry. You should use `toast.view.backgroundView.backgroundColor` instead of using `toast.view.backgroundColor`.

**Comment by ArtworkAD** [comment]
@devxoul there is no backgroundView property in toast.view

**Comment by devxoul** [comment]
Oh deer, I've just made a new release(1.2.5).

**Comment by ArtworkAD** [comment]
Thank you it works.

**Comment by devxoul** [comment]
:smile::+1:
