### ISSUE TITLE
repeat execute JLToast.makeText().show

### ISSUE THREAD

**Issue by hengchengfei** [devxoul/JLToast#40]
when repeat execute,

for example,executed for 10 times in a second,it will show 10 times.

**Comment by devxoul** [comment]
@hengchengfei,
Could you please explain more detail to me?
Thanks.

**Comment by hengchengfei** [comment]
我的意思是，

连续点击弹出按钮，也就是连续调用JLToast.makeText()。

比如非常快的点击10次，会连续出来10个信息窗口。

而我希望在前一个弹出窗口还没消失的时候，不能再弹出窗口了。

但是我没发判断前一个窗口有没消失。

**Comment by hengchengfei** [comment]
repeat click the button，for example 10 times，then Toast view 10 times。

i want to show the next toast after the previous toast hide。

**Comment by devxoul** [comment]
Do you want 'hide previous toast and show new toast'?

**Comment by hengchengfei** [comment]
Yes

**Comment by devxoul** [comment]
That's not supported now in official. However you can do with this:

```swift
previousToast.finish()
previousToast.view.removeFromSuperview()
// then show new toast
```

**Comment by uknowmeright** [comment]
here is some code that might help. It doesn't work in every situation but it might help you develop something fully functional: 

`    var toasts = [JLToast]()
    
    func removeTheToast(toast: JLToast){
        for theToast in self.toasts{
            if theToast != toast {
                theToast.finish()
                theToast.view.removeFromSuperview()
            }
        }
    }`

**Comment by devxoul** [comment]
Hey guys, thanks for waiting. #74 might help.
