### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by saturnial** [devxoul/JLToast#44]
Skipped building JLToast due to the error:
Dependency "JLToast" has no shared framework schemes for any of the platforms: iOS

Can you make a framework so as to support building via carthage?

**Comment by devxoul** [comment]
@saturnial, Sorry for delay!
I've just made a new release 1.3.2 which support Carthage.

Thanks.

**Comment by saturnial** [comment]
Cool. Thanks!

**Comment by devxoul** [comment]
:smile:
