### ISSUE TITLE
show() method should remove previous toasts from the UI

### ISSUE THREAD

**Issue by confile** [devxoul/JLToast#48]
If you call ``makeText().show()`` many times in a row for example, when the user is trying to send data and you show a toast message.  In case the user tapped the button which triggers the toast many times the UI receives a lot of toast. 

Could you manage it somehow to remove previous toast when toasts are still in the UI and you want to show a new toast?

**Comment by devxoul** [comment]
JLToast originally designated to follow Android Toast's behavior. Currently you can dismiss previous toast by call `finish()` to itself. (#40)

I'm working on making a new interface to access current toast and dismiss.

Thanks!

**Comment by andreswebde** [comment]
I don't see it as any issue actually, i am an android developer and it this is the most exact android toast i've ever seen, thanks a lot man, saved my day since i am new to swift!!

**Comment by devxoul** [comment]
@andreswebde, thanks. I'm trying to make JLToast to follow the interface of Android's Toast :)
