### ISSUE TITLE
Toast above keyboard disappears when keyboard is closed

### ISSUE THREAD

**Issue by ArtworkAD** [devxoul/JLToast#50]
So I have a toast above the keyboard but it disappears instantly when the keyboard is closed. I experience this in iOS 9 and swift 2. I think there was no problem with iOS 8.

Related: https://github.com/devxoul/JLToast/issues/31

**Comment by devxoul** [comment]
Hi! Thank you for reporting. Would you please check #52? I think this will perfectly!

**Comment by ArtworkAD** [comment]
@devxoul Hi! I tried your pull request, the actual problem with the disappearing toast is solved! However I cannot update to 1.3.2 because of this issue: https://github.com/devxoul/JLToast/issues/53
