### ISSUE TITLE
v1.3.2 changes statusbar text color from white to black

### ISSUE THREAD

**Issue by ArtworkAD** [devxoul/JLToast#53]
Just noticed that when the toast appears the status bar text color changes from white to black. Statusbar style is set to UIStatusBarStyleLightContent in info.plist.

**Comment by devxoul** [comment]
How did you install JLToast?

**Comment by ArtworkAD** [comment]
@devxoul via cocoapods

**Comment by devxoul** [comment]
Hmm that's odd. I'll check it soon.

**Comment by lggdance** [comment]
Same problem here, also installed via cocoapods.

**Comment by devxoul** [comment]
Hmm. Could anyone please make example project? I cannot reproduce the bug.
Tested with iPhone simulator with OS 8.4 and 9.1, iPhone 6S (JLToast 1.3.2 via CocoaPods)

**Comment by ArtworkAD** [comment]
@devxoul example project: https://github.com/ArtworkAD/ToastTest The problem first appeared with the update from 1.3.1 to 1.3.2. 

Note: in Info.plist I have set **Status bar style** to UIStatusBarStyleLightContent and **Status bar tinting parameters** to -> **Navigation Bar** -> **Style** to default, **Translucent** to no

The navigation bar style in storyboard is set to black. Now when you show the toast the white status bar color gets black.

**Comment by devxoul** [comment]
Hey guys!
I was available to reproduce the bug. #59 will fix the issue, please try with it!
If it works, I'll merge the PR and make a new release as soon as possible.
Thanks to @ArtworkAD.

**Comment by ArtworkAD** [comment]
@devxoul it solves the status bar text problem :+1: . But it again creates the toast under keyboard problem. If keyboard is visible the toast will appear under it and is not visible.

**Comment by devxoul** [comment]
How did you setup with #59? It seemed work for me...

![simulator screen shot dec 12 2015 4 38 50 pm](https://cloud.githubusercontent.com/assets/931655/11760837/d56c4066-a0ee-11e5-9674-93080b6dc993.png)

**Comment by devxoul** [comment]
Hmm, how did you setup #59? It seemed work for me. (status bar and keyboard)

![simulator screen shot dec 12 2015 4 40 48 pm](https://cloud.githubusercontent.com/assets/931655/11760843/1d53979e-a0ef-11e5-9845-0779fa13ea54.png)

**Comment by ArtworkAD** [comment]
@devxoul when the toast appears above the keyboard, close the keyboard, open it again and show another toast. You will notice that the toast now will be under the keyboard. It is strange, the first toast is always above the keyboard but the second is under it.

**Comment by devxoul** [comment]
@ArtworkAD, thank you for waiting. #60 could be the solution for the problem!

**Comment by ArtworkAD** [comment]
@devxoul :+1: it works :smile: please merge and release!

**Comment by devxoul** [comment]
@ArtworkAD Released [1.3.4](https://github.com/devxoul/JLToast/releases/tag/1.3.4)
