### ISSUE TITLE
Custom UIColors for background colors

### ISSUE THREAD

**Issue by pacificanfog0** [devxoul/JLToast#54]
Hey,

I'm having a weird issue:

    let toast: JLToast = JLToast()
    toast.text = "Some text here."
    toast.duration = JLToastDelay.LongDelay
    toast.view.backgroundView.backgroundColor = UIColor(red: 77, green: 228, blue: 199, alpha: 1)
    toast.show()

The toast does not show up/Is not displayed. 

While the same code as above, but with:

    ...
    toast.view.backgroundView.backgroundColor = UIColor.redColor()
    ...

This displays with a nice red background. 

I'm not really sure what's going on here, but any help would be greatly appreciated.

**Comment by devxoul** [comment]
Hi @pacificanfog0!
UIColor takes RGB in range from 0 to 1, not from 0 to 255.

You should do this:

```swift
UIColor(red: 77 / 255.0, green: 228 / 255.0, blue: 199 / 255.0, alpha: 1)
```

![simulator screen shot dec 3 2015 6 26 06 pm](https://cloud.githubusercontent.com/assets/931655/11556648/6f8c6ffa-99eb-11e5-90ee-8a50fa0107c2.png)

Hope it could be helpful for you!

**Comment by pacificanfog0** [comment]
Thank you very much, sorry for overlooking that! It helps a lot.

**Comment by devxoul** [comment]
No problem :smile:
