### ISSUE TITLE
Toast view still uses screen width when in split screen mode

### ISSUE THREAD

**Issue by mikewalkerjr** [devxoul/JLToast#55]
On the iPad Air 2 and iPad Mini 4, the toast messages don't take into account the application view's width. It instead appears to be using the screen width. When I have a split screen, the toast is cut off where the split screen starts.

**Comment by itlijunjie** [comment]
Changing current JLToastView and JLToastWindow frame by observer UIApplicationDidBecomeActiveNotification.
Using JLToastWindow.sharedWindow.frame.size in JLToastView.updateView().

**Comment by devxoul** [comment]
@itlijunjie, #76 fixes it. I'll soon make a new release :)

**Comment by itlijunjie** [comment]
👍
