### ISSUE TITLE
Toast.show() invisible

### ISSUE THREAD

**Issue by TThana** [devxoul/JLToast#56]
The toast invisible now,but earlier it was visible

**Comment by TThana** [comment]
not work with iAd, 
self.canDisplayBannerAds = true

**Comment by devxoul** [comment]
@TThana, which version are you using?

**Comment by devxoul** [comment]
@TThana, could you please try with 1.3.3 version of JLToast?

**Comment by devxoul** [comment]
Close this issue due to no response. Please re-open if you're available to reproduce the issue :)
