### ISSUE TITLE
Doesn't work after TouchID

### ISSUE THREAD

**Issue by mani47** [devxoul/JLToast#57]
For some reason if I use LocalAuthentication and TouchID in some view controller, Toast will not work after that in any other view controller. This is my sample code:

    let context = LAContext()
    var error: NSError?
    let reasonString = "Authentication is needed to complete the action."
    if context.canEvaluatePolicy(LAPolicy.DeviceOwnerAuthenticationWithBiometrics, error: &error) {
            [context .evaluatePolicy(LAPolicy.DeviceOwnerAuthenticationWithBiometrics, localizedReason: reasonString, reply: { (success: Bool, evalPolicyError: NSError?) -> Void in
    
     })]

and after this toast will not work, even when you push to other view controllers until you kill the app completely. I'm on iOS 9.1, Swift 2.0, JLToast 1.3.2

**Comment by devxoul** [comment]
Could you please provide me the full source code using JLToast?

**Comment by mani47** [comment]
I have created this project to showcase the problem:

https://github.com/mani47/showcase-JLToast-bug

 It has 5 view controllers on all viewDidLoad events I show a sample toast message, in third view controller it requires TouchID and on success redirects user to forth view controller and in forth view controller it doesn't show the toast message this is the problem.

but interesting enough in fifth view controller toast message appears again while in my app in all other view controllers after touch id toast message doesn't show up.

**Comment by devxoul** [comment]
@mani47, thanks! I was available to reproduce the bug.
#52 might fix it. I just released 1.3.3 version which contains #52 PR.

Try again with that version and please let me know if it works or not. :smile:

**Comment by mani47** [comment]
You are awesome! Thank you for the great work with JLToast.
