### ISSUE TITLE
Black screen appears for a time being on device rotation. 

### ISSUE THREAD

**Issue by suniljakhar** [devxoul/JLToast#58]
Once toast message is appears on screen, after that if user rotates the device then for a time being screen become black.

**Comment by devxoul** [comment]
@suniljakhar, what did you mean 'screen become black'?
It'll be more easy to understand if there's a screenshot. :smile:

**Comment by suniljakhar** [comment]
I think UIWindow is not there for a time being on rotation. You can try yourself in demo project also. First let the toast message display and then rotate the device to see the issue.

**Comment by devxoul** [comment]
@suniljakhar, did you mean this 'black' background?

![simulator screen shot dec 23 2015 2 16 56 pm](https://cloud.githubusercontent.com/assets/931655/11971373/ed62f414-a97f-11e5-9764-7f13f7a3678b.png)

**Comment by suniljakhar** [comment]
No

**Comment by suniljakhar** [comment]
PFA.....
![simulator screen shot 23-dec-2015 3 05 18 pm](https://cloud.githubusercontent.com/assets/14994690/11974085/c8d17236-a986-11e5-9b28-704b3f470a0d.png)

**Comment by suniljakhar** [comment]
![simulator screen shot 23-dec-2015 3 05 28 pm](https://cloud.githubusercontent.com/assets/14994690/11974088/ddae7a50-a986-11e5-999f-938697f4c50d.png)

**Comment by devxoul** [comment]
Which version of JLToast and iOS did you test with?

**Comment by suniljakhar** [comment]
JLToast latest one and iOS 8.4 and above with swift.

**Comment by suniljakhar** [comment]
Any update.....?

**Comment by devxoul** [comment]
@suniljakhar, sorry for delay! #64 fixes the issue, and this will be shipped with 1.3.5 release :)

**Comment by suniljakhar** [comment]
Thanks!!!!!!
