### ISSUE TITLE
ITMS-90362 error on itunes upload

### ISSUE THREAD

**Issue by dlr2** [devxoul/JLToast#65]
Nevermind, I fixed this issue ... Not sure how to delete the issue entirely though.

**Comment by devxoul** [comment]
@dlr2, could you please tell me more about your issue?

**Comment by dlr2** [comment]
The problem was that the SK version was set to 7.0 - but had to be at least
8.0 to iTunes upload. I fixed it right after I posted but I did not know
how to delete the whole issue. Sorry.

**Comment by devxoul** [comment]
How did you install JLToast?

**Comment by dlr2** [comment]
As a pod for an iOS SDK9 app. But the pod installed citing SDK 7 - I
changed that and it worked fine.

**Comment by devxoul** [comment]
@dir2, Which did you mean: 'SDK' or 'Minimum Deployment Target'?

**Comment by dlr2** [comment]
Oh right I meant - Minimum Deployment Target - sorry

**Comment by devxoul** [comment]
@dir2, you cannot install Swift libraries via CocoaPods if your Minimum Deployment Target is 7. For details, see the [CocoaPods blog post](http://blog.cocoapods.org/CocoaPods-0.36/).

If you want to use JLToast in iOS 7 projects, consider using [CocoaSeeds](https://github.com/devxoul/CocoaSeeds). You can follow the [instruction on README](https://github.com/devxoul/JLToast#installation)
