### ISSUE TITLE
설치법이 어떻게 되나요?

### ISSUE THREAD

**Issue by goodsogi** [devxoul/JLToast#66]
안녕하세요. 초보 아이폰 개발자입니다. 

어떻게 설치해야 하나요? Podfile을 하나 만들어서 pod 'JLToast', '~> 1.3'를 입력하고 터미널에서 pod install을 입력했습니다. Pods폴더안에 JLToast 파일들은 들어갔는데 ViewController에서 JLToast.makeText("Basic JLToast").show()를 입력하니 JLToast를 찾을 수 없다고 하네요. 

뭐가 잘못된 걸까요? 도움 부탁드립니다.

**Comment by devxoul** [comment]
안녕하세요.
파일 상단에 프레임워크를 임포트하는 구문을 작성해주셔야 합니다.

```swift
import JLToast

JLToast.makeText("Basic JLToast").show()
```

그리고, 이곳은 한국어 사용자들만을 위한 공간이 아니기 때문에 다음부터는 영문으로 작성해주시면 감사하겠습니다.

**Comment by goodsogi** [comment]
I wrote "import JLToast" on view controller file. Xcode tells me No such model 'JLToast'.

I use Xcode version 7.2.1, Swift 2.0 and OSX El Capitan.

**Comment by goodsogi** [comment]
No such Module. And Cocoapods version is 0.39.0.

**Comment by devxoul** [comment]
@goodsogi, are you working with **`YourApp.xcodeproj`** file? If true, you should use **`YourApp.xcworkspace`** file instead.

**Comment by goodsogi** [comment]
I opened myApp.xcworkspace. This time Xcode tell me Can not load underlying module for 'JLToast'.

**Comment by devxoul** [comment]
@goodsogi, Which minimum deployment target version of your project?

**Comment by goodsogi** [comment]
I tried deployment target 9.2 and 8.0. Same result.

**Comment by devxoul** [comment]
Did you add `use_frameworks!` to your Podfile?

**Comment by goodsogi** [comment]
Yes I did. 

I have no problem with other libraries: Google map, Alamofire, etc using Cocoapods.

**Comment by devxoul** [comment]
It seemed not a JLToast issue but Xcode issue. Have you tried clean build?

**Comment by goodsogi** [comment]
Yes I did. 

Have you tried you library at Xcode 7.2.1?

**Comment by devxoul** [comment]
I'm using 7.2.1

**Comment by devxoul** [comment]
If clean build doesn't work, try building your project first **without** using any JLToast in your code.

Related discussions:

- https://github.com/Alamofire/Alamofire/issues/441
- https://github.com/Alamofire/Alamofire/issues/122

**Comment by goodsogi** [comment]
Ok I tried clean build folder. Now it works. Thanks.

**Comment by devxoul** [comment]
Cool :smile::+1:
