### ISSUE TITLE
SWRevealViewController 와의 UIbarStyle 문제

### ISSUE THREAD

**Issue by CenoX** [devxoul/JLToast#68]
SWRevealViewController ( [https://github.com/John-Lluch/SWRevealViewController](https://github.com/John-Lluch/SWRevealViewController)) ) 로 만든 frontView와 rearView 에서의 UIBarStyle 의 속성 값이 다를 때 Front(.Black) 와 Rear(.Default) 를 오갈 때 statusBar 가 자동으로 스타일을 변경합니다만, 뷰 내에서 JLToas를 통한 toast 를 한번이라도 띄울 시, Rear 뷰의 statusBar 가 Front 뷰의 statusBar 속성값으로 고정됩니다.

사진을 첨부할 곳이 없어 개인 블로그로 사진첨부를 대신 하겠습니다
[http://ceno-loid.tistory.com/45](http://ceno-loid.tistory.com/45)

I built a project with SWRevealViewController [(LINK)](https://github.com/John-Lluch/SWRevealViewController) and JLToast.
When the property of rearView’s UIBarStyle is different from frontView’s one (rearViewBarStyle: .Default, frontViewBarStyle: .Black) UIStatusBar changes its own style itself, but if JLToast is shown more than one time on view, frontView’s UIBarStyle overrides rearView’s one.

Here is the link, the photo posted with my own blog.
[LINK](http://ceno-loid.tistory.com/45)

**Comment by devxoul** [comment]
statusbar 와 관련된 #53 이슈는 확인해보셨는지요? 만약 다른 문제라고 판단되시면, 1) 사용중인 JLToast 버전과, 2) 버그를 쉽게 재현할 수 있는 예시 프로젝트를 만들어서 공유해주시면 빠른 문제 해결에 도움이 될 것 같습니다.

참고로, GitHub Issue 작성시에는 이미지 파일을 에디터에 드래그 앤 드랍하여 이미지를 첨부할 수 있습니다. 그리고 작성해주신 URL들은 잘못된 곳으로 링크되어있습니다.

덧붙여서, 이곳은 한국어 사용자들만을 위한 공간이 아닙니다. 되도록이면 영문으로 작성해주시면 감사하겠습니다.

**Comment by CenoX** [comment]
(영어가 미숙한 점 죄송합니다.)
I used 'JLToast' with CocoaPods with version (1.3.5).
[Link](https://github.com/CenoX/SampleProj) Here is the sample project with errors that I said.

App's UIBarStyle is .Default option and the main view's UIBarStyle is .Black.
When I call JLToast, It seems the main view's UIBarStyle overrides the whole app's UIBarStyle.

**Comment by devxoul** [comment]
@CenoX, thanks for understanding. It looks more complicated issue that I first thought. I'll take a look for it. Thanks for reporting!

**Comment by devxoul** [comment]
Hi, thank you for waiting. #73 can fix the problem. You can test it by updating your [SampleProj's **`Podfile`**](https://github.com/CenoX/SampleProj/blob/master/Podfile):

```ruby
use_frameworks!

target 'SampleProj' do

pod 'JLToast', :git => 'https://github.com/devxoul/JLToast', :branch => 'statusbar-style'

end
```

Please try it and let me know if it works or not :)

**Comment by CenoX** [comment]
Thank you for your hard working!!
I've done testing with your new options, and it works perfectly as I want.

Separately, making issues in github was first time for me, and I want thank you for your advice about using github.

![simulator screen shot 2016 4 11 7 55 48](https://cloud.githubusercontent.com/assets/5639358/14425078/993507c8-001f-11e6-9eea-8983181c20e2.png)
![simulator screen shot 2016 4 11 7 55 50](https://cloud.githubusercontent.com/assets/5639358/14425081/9e223012-001f-11e6-832d-3ddcac627c33.png)

**Comment by devxoul** [comment]
@CenoX, glad to hear that :) I'll merge the PR and make a new release (maybe 1.4.0) soon.
