### ISSUE TITLE
Using .show() adds status bar to my non-status bar using app. 

### ISSUE THREAD

**Issue by sshadmand** [devxoul/JLToast#69]
Here's a screenshot of how the status bar was added to my app after calling .show(). 

https://www.evernote.com/l/AA4c-N9TxclOrZCqYGBQWsWAxb7aFqAOpnY

Is there a way to tell JLToast not to apply the status bar to the view when displaying?

Note: My views all have 

```
    override func prefersStatusBarHidden() -> Bool {
        return true
    }
```

implemented.

**Comment by yybutcher** [comment]
JLToastWindowRootViewController ->
add:

```
private override func prefersStatusBarHidden() -> Bool {
        return UIApplication.sharedApplication().statusBarHidden
}
```

**Comment by devxoul** [comment]
@sshadmand, #70 will fix it. I'll make a new release soon. (Thanks to @yybutcher)
