### ISSUE TITLE
swift 2.2?

### ISSUE THREAD

**Issue by ivanruizscm** [devxoul/JLToast#72]
There will be a release for swift 2.2?

**Comment by devxoul** [comment]
@ivanruizscm, JLToast currently works perfectly with Swift 2.2. I'll make a new release to get rid of deprecation warnings as soon as possible :)

**Comment by ivanruizscm** [comment]
Yes, i'm getting warnings in travis:
Compiling JLToastCenter.swift
⚠️  /Users/travis/build/scmspain/next-visit-ios/Pods/JLToast/JLToast/JLToastCenter.swift:40:23: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
            selector: "deviceOrientationDidChange:",
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
▸ Compiling JLToastView.swift
▸ Compiling JLToastWindow.swift
⚠️  /Users/travis/build/scmspain/next-visit-ios/Pods/JLToast/JLToast/JLToastWindow.swift:37:23: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
            selector: "bringWindowToTop:",
                      ^~~~~~~~~~~~~~~~~~~
▸ Compiling JLToast.swift
▸ Compiling JLToastCenter.swift
⚠️  /Users/travis/build/scmspain/next-visit-ios/Pods/JLToast/JLToast/JLToastCenter.swift:40:23: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
            selector: "deviceOrientationDidChange:",
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

And so on, if you want i can PR it or do it by yourself, thx!

**Comment by devxoul** [comment]
@ivanruizscm, thank you for waiting. #75 resolves it :)

**Comment by ivanruizscm** [comment]
awesome!

**Comment by devxoul** [comment]
@ivanruizscm, #75 has been shipped in 1.4.0 release :smile:
